version: "3.9"

services:
  backend:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    command: npm run start

  frontend:
    build: ./src
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app
    command: npm run dev